name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          echo "Debug: Attempting to trigger Jenkins job..."
          curl -v -X POST \
          "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/build" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}"


#Github Actions Update
